// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.27.1
// source: ynisonstate/device_info_header.proto

package ynisonstate

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Хэдер Ynison-Device-Info, в котором устройство представляется о себе в начале сеанса.
// Его передача условно опциональна, но крайне желательна как для походов в ynison-hub, так и в ynison-redirector
// Информация должна совпадать с полями из DeviceInfo, передаваемыми в этом же сеансе в UpdateFullState.
//
// Хэдер представляет собой сериализованное proto-сообщение, упакованное в
// в base64 со стандартным алфавитом (не url-safe), без паддинга и без переносов строк.
// Пример в java: Base64.getEncoder().withoutPadding().encodeToString(proto.toByteArray())
//
// Эта информация будет использоваться для улучшения аналитики по возникающим проблемам.
type YnisonDeviceInfoHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Тип устройства. Оригинальное поле DeviceInfo#type
	Type DeviceType `protobuf:"varint,1,opt,name=type,proto3,enum=ynison_state.DeviceType" json:"type,omitempty"`
	// Информация о клиентском приложении подключенного устройства. Оригинальное поле DeviceInfo#app_name
	AppName string `protobuf:"bytes,2,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	// Информация о версии клиентского приложения подключенного устройства. Оригинальное поле DeviceInfo#app_version
	AppVersion string `protobuf:"bytes,3,opt,name=app_version,json=appVersion,proto3" json:"app_version,omitempty"`
}

func (x *YnisonDeviceInfoHeader) Reset() {
	*x = YnisonDeviceInfoHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ynisonstate_device_info_header_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *YnisonDeviceInfoHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YnisonDeviceInfoHeader) ProtoMessage() {}

func (x *YnisonDeviceInfoHeader) ProtoReflect() protoreflect.Message {
	mi := &file_ynisonstate_device_info_header_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YnisonDeviceInfoHeader.ProtoReflect.Descriptor instead.
func (*YnisonDeviceInfoHeader) Descriptor() ([]byte, []int) {
	return file_ynisonstate_device_info_header_proto_rawDescGZIP(), []int{0}
}

func (x *YnisonDeviceInfoHeader) GetType() DeviceType {
	if x != nil {
		return x.Type
	}
	return DeviceType(0)
}

func (x *YnisonDeviceInfoHeader) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *YnisonDeviceInfoHeader) GetAppVersion() string {
	if x != nil {
		return x.AppVersion
	}
	return ""
}

var File_ynisonstate_device_info_header_proto protoreflect.FileDescriptor

var file_ynisonstate_device_info_header_proto_rawDesc = []byte{
	0x0a, 0x24, 0x79, 0x6e, 0x69, 0x73, 0x6f, 0x6e, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2f, 0x64, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x79, 0x6e, 0x69, 0x73, 0x6f, 0x6e, 0x5f, 0x68,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x1a, 0x1d, 0x79, 0x6e, 0x69, 0x73, 0x6f, 0x6e, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x2f, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x82, 0x01, 0x0a, 0x16, 0x59, 0x6e, 0x69, 0x73, 0x6f, 0x6e, 0x44,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12,
	0x2c, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e,
	0x79, 0x6e, 0x69, 0x73, 0x6f, 0x6e, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a,
	0x08, 0x61, 0x70, 0x70, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x61, 0x70, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x70, 0x70, 0x5f,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61,
	0x70, 0x70, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x42, 0x68, 0x0a, 0x1f, 0x63, 0x6f, 0x6d,
	0x2e, 0x79, 0x61, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x2e, 0x79, 0x6e,
	0x69, 0x73, 0x6f, 0x6e, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x01, 0x5a, 0x43,
	0x61, 0x2e, 0x79, 0x61, 0x6e, 0x64, 0x65, 0x78, 0x2d, 0x74, 0x65, 0x61, 0x6d, 0x2e, 0x72, 0x75,
	0x2f, 0x6d, 0x75, 0x73, 0x69, 0x63, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x6d,
	0x75, 0x73, 0x69, 0x63, 0x2d, 0x79, 0x6e, 0x69, 0x73, 0x6f, 0x6e, 0x2f, 0x6d, 0x61, 0x69, 0x6e,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x79, 0x6e, 0x69, 0x73, 0x6f, 0x6e, 0x68, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ynisonstate_device_info_header_proto_rawDescOnce sync.Once
	file_ynisonstate_device_info_header_proto_rawDescData = file_ynisonstate_device_info_header_proto_rawDesc
)

func file_ynisonstate_device_info_header_proto_rawDescGZIP() []byte {
	file_ynisonstate_device_info_header_proto_rawDescOnce.Do(func() {
		file_ynisonstate_device_info_header_proto_rawDescData = protoimpl.X.CompressGZIP(file_ynisonstate_device_info_header_proto_rawDescData)
	})
	return file_ynisonstate_device_info_header_proto_rawDescData
}

var file_ynisonstate_device_info_header_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ynisonstate_device_info_header_proto_goTypes = []interface{}{
	(*YnisonDeviceInfoHeader)(nil), // 0: ynison_header.YnisonDeviceInfoHeader
	(DeviceType)(0),    // 1: ynison_state.DeviceType
}
var file_ynisonstate_device_info_header_proto_depIdxs = []int32{
	1, // 0: ynison_header.YnisonDeviceInfoHeader.type:type_name -> ynison_state.DeviceType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ynisonstate_device_info_header_proto_init() }
func file_ynisonstate_device_info_header_proto_init() {
	if File_ynisonstate_device_info_header_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ynisonstate_device_info_header_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*YnisonDeviceInfoHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ynisonstate_device_info_header_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ynisonstate_device_info_header_proto_goTypes,
		DependencyIndexes: file_ynisonstate_device_info_header_proto_depIdxs,
		MessageInfos:      file_ynisonstate_device_info_header_proto_msgTypes,
	}.Build()
	File_ynisonstate_device_info_header_proto = out.File
	file_ynisonstate_device_info_header_proto_rawDesc = nil
	file_ynisonstate_device_info_header_proto_goTypes = nil
	file_ynisonstate_device_info_header_proto_depIdxs = nil
}
